### ISSUE TITLE
BUG: Panel deprecated; change HDFStore to store DataFrame objects instead

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#39]
In file main.py:

```
agent_storelist = {}  # all the agent HDF files are stored in this dict
    for key, value in infiles.items():
        f_p = str(inpath) + "/" + str(value)
        agent_storelist[key] = pd.io.pytables.HDFStore(f_p)

for agentname, agentstore in agent_storelist.items():
    for key in agentstore.keys():  # go through sets and runs in the HDF file
        pnl = agentstore.select(key)
    ....
[208] df = pnl.to_frame()  # convert panel to Dataframe
```
throws this error:

```
Traceback (most recent call last):
  File "/media/sander/DataStorage-2/Software/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py", line 1693, in _create_storer
    cls = _TABLE_MAP[tt]
KeyError: 'appendable_panel'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 227, in <module>
    df = pd.read_hdf(agentstore, key='/set_1_run_1_iters') # this uses: store.select(key)
  File "/media/sander/DataStorage-2/Software/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py", line 425, in read_hdf
    return store.select(
  File "/media/sander/DataStorage-2/Software/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py", line 824, in select
    s = self._create_storer(group)
  File "/media/sander/DataStorage-2/Software/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py", line 1695, in _create_storer
    raise error("_TABLE_MAP") from err
TypeError: cannot properly create the storer for: [_TABLE_MAP] [group->/set_1_run_1_iters (Group) '',value-><class 'NoneType'>,format->None
```

The problem is that the Panel format of pandas is deprecated.
The HDF5 files contain HDFStore objects (data groups) that are of type: 'appendable_panel'.

But pytables.py only allows these types:

```
_TABLE_MAP = {
            "generic_table": GenericTable,
            "appendable_series": AppendableSeriesTable,
            "appendable_multiseries": AppendableMultiSeriesTable,
            "appendable_frame": AppendableFrameTable,
            "appendable_multiframe": AppendableMultiFrameTable,
            "worm": WORMTable,
}
```

**Comment by svdhoog** [comment]
# Step 1: Fixed db to h5 conversion

File: db_hdf5_v1.py, db_hdf5_v2.py

Throws an error in func `dframes.to_panel()`, because it no longer allows to convert a DataFrame object to a Panel object (due to deprecation of Panel in pandas).

```
File "db_hdf5_v1.py", line 102, in gen_hdf
    store[s] = gendp(dfa) #original: store a pandas Panel object
  File "db_hdf5_v1.py", line 74, in gendp
    dp = dframes.to_panel()
  File "/media/sander/DataStorage-2/Software/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_panel'
```
# Solution

No longer convert DataFrame objects to a Panel object.

* See for the fix.
* Also included: compression switch
* Set the chunksize used for HDFStore compression
* Always use 'table' format for pytables (not  'fixed', because it causes incorrect storage of the data in the h5 files).

**Comment by svdhoog** [comment]
# Step 2: Fix h5_agentwise.py

* TODO: Fix the script to combine the set-wise h5 files to an agent-wise h5 file.

```
TypeError: cannot properly create the storer for: [_TABLE_MAP] [group->/Agent (Group) '',value-><class 'NoneType'>,format->None
```
Same error as above for the simple conversion scripts from DB to h5.
