### ISSUE TITLE
Ways to execute the FLAViz main executable script (main.py)

### ISSUE THREAD

**Issue by svdhoog** [svdhoog/FLAViz#7]
It should be possible to execute the FLAViz main executable script (main.py) in these ways:

1. CD into the folder with the config yaml files and execute main.py from there:
```
# cd $CONFIG_FOLDER
# python3 $FLAVIS_PATH/src/visualisation_scripts/main.py ./
```

2. CD into the flaviz src folder and execute main.py from there, using a relative path to the config folder:
```
# cd $FLAVIS_PATH/src/visualisation_scripts
# python3 main.py ../config
```

3. CD into the flaviz src folder and execute main.py from there, using a hard-coded path to the config folder:
```
# cd $FLAVIS_PATH/src/visualisation_scripts
# python3 main.py $CONFIG_FOLDER
```

4. Execute from anywhere, using a hard-coded path for main.py, and also use a hard-coded path for the config folder:
```
# python3 $FLAVIS_PATH/src/visualisation_scripts/main.py $CONFIG_FOLDER
```

**Comment by svdhoog** [comment]
Results
--
*Note:* These results were obtained with a large (21 GB) h5 file, so there could be errors in this input file. To be checked.

1. gives an error:
```
Traceback (most recent call last):
  File "/upb/departments/pc2/users/e/etace004/files-server/GIT/GitLab/UIC-ABM-Estimation/code/Eurace_Unibi_Financial_Fragility_Network_Model_1.0/Scripts/main/flame-viz/src/visualisation_scripts/main.py", line 145, in <module>
    d = pd.concat(df_list)  # Add each dataframe from panel into a main dataframe containing all sets and runs
  File "/cm/shared/apps/pc2/ANACONDA/3-5.0.0.1/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/cm/shared/apps/pc2/ANACONDA/3-5.0.0.1/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

2. gives an error:
```
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    d = pd.concat(df_list)  # Add each dataframe from panel into a main dataframe containing all sets and runs
  File "/cm/shared/apps/pc2/ANACONDA/3-5.0.0.1/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 206, in concat
    copy=copy)
  File "/cm/shared/apps/pc2/ANACONDA/3-5.0.0.1/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 239, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
Closing remaining open files:/scratch/hpc-prf-etace/svdhoog/shared_data/Estimation_Dataset_1/calibration-mode-3/h5/Eurostat.h5...done
```
3. gives an error:
```
Traceback (most recent call last):
  File "main.py", line 145, in <module>
    d = pd.concat(df_list)  # Add each dataframe from panel into a main dataframe containing all sets and runs
  File "/usr/lib/python3/dist-packages/pandas/tools/merge.py", line 929, in concat
    verify_integrity=verify_integrity)
  File "/usr/lib/python3/dist-packages/pandas/tools/merge.py", line 974, in __init__
    raise Exception('All objects passed were None')
Exception: All objects passed were None
Closing remaining open files:/media/sander/DataStorage1/GIT/GitHub/FLAViz@svdhoog/FLAViz/results_test2/Eurostat.h5...done/media/sander/DataStorage1/GIT/GitHub/FLAViz@svdhoog/FLAViz/results_test2/CentralBank.h5...done/media/sander/DataStorage1/GIT/GitHub/FLAViz@svdhoog/FLAViz/results_test2/Firm.h5...done
```
4. gives an error:
```

```

**Comment by 0xfabi** [comment]
I've added repo_name: 'FLAViz' to the config.yaml because I need an anchor to identify the correct path of the repository. 
Now all 4 cases should work.
